#+TITLE:Addendum to Mapping Urban Tree Cover in Wisconsin
#+AUTHOR: Tedward Erker
#+email: erker@wisc.edu
#+PROPERTY: header-args:R :session *R* :cache no :results output :exports both :tangle yes
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
------------

* Overview
This proposal expands upon the original proposal "Approaches to
Mapping Urban Tree Cover in Wisconsin for the Urban FIA".  Work from
the previous proposal has resulted in a method to map urban tree cover
with greater than 84% accuracy at pixel level, and greater accuracies
as scale increases (up to 95% accuracy at areas of 4 hectares).  We
found NAIP imagery greatly surpasses pan-sharpened SPOT imagery in
classification accuracy due to greater spatial resolution and image
quality.  However, because NAIP imagery is aquired throughout the
growing season and at different times of day, imagery varies from city
to city across Wisconsin and classification models trained on Madison
imagery had accuracies as low as 82% (Wausau) and 66% (City of
Marinette).

Here we propose to use the method developed for Madison and reliably
apply it to every urban area in the State of Wisconsin.  To do so we
will collect additional training data across the state to address the
differences in imagery across the state.  Landcover classes will be
"Tree", "Grass/Herbaceous", and "Impervious/Bare Soil" - derived from
NAIP imagery - and "Agriculture","Water", "Wetland" - derived from
ancillary data sources.  We will add a buffer of 1km to the urban
areas to allow for future analyses of urban expansion.  In addition to
incorporating training data from across the state, we will test
improvements to building classification models such as tuning
(adjusting hyperparameters for machine learning algorithms), feature
selection and "bagging" (techniques to identify and use only the
variables/features that provide the highest accuracy).  We will assess
the accuracy of the landcover maps using Google Earth.  A human
interpreter will identify the landcover class of at least 50 randomly
located points for each of at least 10 Wisconsin cities not used in
training.

* Products
1) A single raster file containing landcover maps for every urban area
   in Wisconsin usable by the Wisconsin DNR and iTree landscape's
   online application.
2) A final report on the methods and accuracy of classification.

* Timeline

| Task                                                                                      | Deadline         |
|-------------------------------------------------------------------------------------------+------------------|
| Select cities for training data that have imagery from each hour of day and month of year | Completed        |
| Rewrite code for multiple training sets and cities                                        | [2016-09-16 Fri] |
| Test improvements to model building - tuning, feature selection, bagging                  | [2016-09-20 Tue] |
| Incorporate all additional training data                                                  | [2016-09-23 Fri] |
| Provide Laura with accuracy assessment shapefiles                                         | [2016-09-23 Fri] |
| Determine best classification model for state                                             | [2016-09-30 Fri] |
| Classify every single urban area in state                                                 | [2016-10-07 Fri] |
| UTC progress meeting                                                                      | [2016-10-07 Fri] |
| Complete accuracy assessment for subset of urban areas across state                       | [2016-10-14 Fri] |
| Complete landcover map as a single raster file                                            | [2016-10-21 Fri] |
| Complete UTC project, Landcover Map and Report                                            | [2016-11-01 Tue] |


* Budget Justification

The budget includes funds to support:

Equivalent of 1 semester of salary for Tedward Erker.  Tedward Erker is a
Ph.D. student in the Townsend lab whose interest in urban forestry
aligns with the Wisconsin DNR's desire for state-wide maps of tree
canopy cover for urban areas.  He is the primary author of the code
used for creating and assessing the accuracy of landcover maps for
Madison, WI.

